### PR TITLE
fix: prevent blacklisted users from messaging in calls

### PR DESCRIPTION
**Pull request by Rexogamer**
this also improves the bl message

### CODE REVIEW

**Comment by turret-dev** [comment]
why'd u do this in a PR

**Comment by Rexogamer** [comment]
for reviewing purposes; I'd rather not touch this pretty important code without another pair of eyes

**Review by turret-dev — APPROVED** [review]
the message changes are fine

**Review by turret-dev — CHANGES_REQUESTED** [review]
user.blacklisted returns a promise (await?)

**Comment by Odyssey346** [comment]
lgtm

**Comment by turret-dev** [comment]
> lgtm

there arent any lgtm alerts wdym

**Review by turret-dev — APPROVED** [review]
everything is all g 👍

**Review by Mitchell3514 — APPROVED** [review]
lgtm

**Pull request merged**
