### PR TITLE
refactor: unify similar embeds

### LINKED ISSUE #287: Unify similar embeds
Right now, our embeds (especially error ones) are scattered and have a lot of minor differences. This is inconsistent and a bit of a mess to maintain. I technically started this in b3ad1e8, but I'm going to unify these embeds in `src/configuration/embeds.js`.

### PR DESCRIPTION
**Pull request by Rexogamer**
This brings several embeds into `embeds.js`.

*Resolves #287*

### CODE REVIEW

**Comment by Mitchell3514** [comment]
Can you fix Codacy

**Comment by Rexogamer** [comment]
I'm not sure how short of importing the embeds file every time. I've exported the embeds the same way as we export the config and aliases...

**Comment by Mitchell3514** [comment]
> I'm not sure how short of importing the embeds file every time. I've exported the embeds the same way as we export the config and aliases...

Seeing as Codacy doesn't see the other imports as an issue, it probably reads the .eslintrc file for defined globals.

**Comment by SunburntRock89** [comment]
why don't we be normal and just not use globals

**Pull request merged**
