### PR TITLE
lgtm fixes

### PR DESCRIPTION
**Pull request by Rexogamer**
The reason I made a separate branch because pushing wasn't working

...I forgot to actually commit the commit

### CODE REVIEW

**Comment by Rexogamer** [comment]
Oh fuck off Hound

**Comment by Mitchell3514** [comment]
What is this

**Comment by Rexogamer** [comment]
A pull request

**Comment by Mitchell3514** [comment]
Where are we on this?

**Comment by Rexogamer** [comment]
conflicts unfortunately, ready will be easy to fix but not message

**Review by Mitchell3514 — APPROVED** [review]

**Pull request merged**
