### PR TITLE
[wip] blackjack

### PR DESCRIPTION
**Pull request by turret-dev**
blackjack for gambling away life savings

### CODE REVIEW

**Comment by Rexogamer** [comment]
I thought this would be a v4 feature

**Comment by turret-dev** [comment]
im impatient

**Comment by Mitchell3514** [comment]
@Rexogamer probably will be

**Comment by turret-dev** [comment]
> I thought this would be a v4 feature

im just gonna add it to v3 first because im impatient to wait for v4 to add it

**Pull request closed without merging**
