### PR TITLE
refactor: change the folder structure

### LINKED ISSUE #278: Redoing folder structure
Currently, the repo is lacking a folder structure. This will be good to have as the codebase gets better and grows with tests, docs, etc.

### PR DESCRIPTION
**Pull request by Mitchell3514**
Added a `src` folder for the code to be located and `assets` for any assets. Also a `docs` folder, but that one will be in place once I write information on how to contribute.

Resolves #278

### CODE REVIEW

**Review by Rexogamer — APPROVED** [review]
Code and folder changes LGTM - wouldn't it make more sense to name the RTD folder just, well, `docs`? Also, will we deploy docs from `development` or `master`?

**Comment by Mitchell3514** [comment]
> Code and folder changes LGTM - wouldn't it make more sense to name the RTD folder just, well, `docs`? Also, will we deploy docs from `development` or `master`?

docs folder will already be for stuff like a `contributing.md`

**Comment by Mitchell3514** [comment]
Actually let me also get rid of these dumb capital letters.

**Comment by Rexogamer** [comment]
> 
> 
> > Code and folder changes LGTM - wouldn't it make more sense to name the RTD folder just, well, `docs`? Also, will we deploy docs from `development` or `master`?
> 
> Docs folder will already be for stuff like a `contributing.md`. Seems best to deploy from master, as that'll be the version the (public) bot is on.

I always assumed stuff like contributing and dev docs would be hosted on RTD too, although maybe under a `dev` subfolder. And yeah, master makes sense

**Review by SunburntRock89 — APPROVED** [review]
We could just be normal and have another repo for docs etc but this works ig

**Comment by Mitchell3514** [comment]
> We could just be normal and have another repo for docs etc but this works ig

Yeah agreed

**Review by turret-dev — CHANGES_REQUESTED** [review]
`refactor: get rid of capital letters` does NOT get rid of all capital letters

**Comment by Rexogamer** [comment]
> 
> 
> `refactor: get rid of capital letters` does NOT get rid of all capital letters

why did you shout then, hypocrisy

**Pull request merged**
