### PR TITLE
refactor: clean up unused files

### LINKED ISSUE #284: Get rid of unused files
Currently, we have files like cache and .houndrc that aren't used.
Having unused files only clutters the repository, so it would be best to remove them.

### PR DESCRIPTION
**Pull request by Rexogamer**
- We're ditching Hound as it's broken and unneccesary, so these config files can go.
- The cache is entirely unused.

*More to come*

Resolves #284

### CODE REVIEW

**Review by SunburntRock89 — COMMENTED** [review]
We should remove this cache (it's kinda badly written, not my best work) **on the condition** that we add better caching.

**Comment by Rexogamer** [comment]
> 
> 
> We should remove this cache (it's kinda badly written, not my best work) **on the condition** that we add better caching.

Sun, I think the reason we're removing it is that it's *entirely unused* - I'm not opposed to a better cache in any way, but still

**Comment by Mitchell3514** [comment]
> We should remove this cache (it's kinda badly written, not my best work) **on the condition** that we add better caching.

I don't think we need caching at all, but this wasn't used in the first place.

**Comment by SunburntRock89** [comment]
> 
> 
> > We should remove this cache (it's kinda badly written, not my best work) **on the condition** that we add better caching.
> 
> I don't think we need caching at all, but this wasn't used in the first place.

I wasn't against removing that one. We should defo keep active calls in memory - it doesn't make sense to pull them from the database every time someone sends a message.

**Review by SunburntRock89 — APPROVED** [review]

**Review by Mitchell3514 — APPROVED** [review]

**Comment by SunburntRock89** [comment]
Well that was good timing

**Pull request merged**
